import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("defines PostgreSQL persistence for the five business models",async()=>{const schema=await readFile(new URL("../prisma/schema.prisma",import.meta.url),"utf8");for(const model of ["Project","Research","Source","Insight","Brief"])assert.match(schema,new RegExp(`model ${model} \\{`));assert.match(schema,/provider = "postgresql"/);assert.match(schema,/ownerId\s+String/)});
test("ships exactly the six fixed research modules",async()=>{const source=await readFile(new URL("../app/lib/data.ts",import.meta.url),"utf8");for(const moduleName of ["BRAND_CONTEXT","MARKET_SIGNALS","TARGET_AUDIENCE","CUSTOMER_PAINS","COMPETITOR_POSITIONING","OPPORTUNITIES_RISKS"])assert.match(source,new RegExp(moduleName));assert.equal((source.match(/\["[A-Z_]+", "[^"]+"\]/g)||[]).length,6)});
test("keeps AI behind an LLMProvider and Provider Factory",async()=>{const contract=await readFile(new URL("../services/ai/llm-provider.ts",import.meta.url),"utf8"),mock=await readFile(new URL("../services/ai/providers/mock-llm-provider.ts",import.meta.url),"utf8"),factory=await readFile(new URL("../services/ai/provider-factory.ts",import.meta.url),"utf8");assert.match(contract,/interface LLMProvider/);assert.match(mock,/class MockLLMProvider implements LLMProvider/);assert.match(factory,/createProvider/);assert.doesNotMatch(mock,/openai/i)});
test("implements source visibility and Markdown export",async()=>{const source=await readFile(new URL("../app/components/brand-scope-app.tsx",import.meta.url),"utf8"),route=await readFile(new URL("../app/api/projects/[id]/brief/route.ts",import.meta.url),"utf8");assert.match(source,/信息来源/);assert.match(route,/text\/markdown/);assert.match(source,/CONFIRMED/);assert.match(source,/保存简报/)});
test("keeps research, insight and brief prompts separate",async()=>{for(const name of ["research","insight","brief"])await readFile(new URL(`../services/ai/prompts/${name}.ts`,import.meta.url),"utf8")});
