import OpenAI from "openai";import { zodTextFormat } from "openai/helpers/zod";import { briefToMarkdown } from "@/app/lib/brief-markdown";import type { LLMProvider } from "../llm-provider";import { aiConfig } from "../config";import { briefResponseSchema, insightResponseSchema, researchResponseSchema } from "../schemas";

export class OpenAILLMProvider implements LLMProvider{
 private client:OpenAI;
 constructor(apiKey:string){this.client=new OpenAI({apiKey,timeout:aiConfig.timeoutMs,maxRetries:aiConfig.maxRetries});}
 private async parse<T>(prompt:string,schema:Parameters<typeof zodTextFormat>[0],name:string){try{const response=await this.client.responses.parse({model:aiConfig.model,input:prompt,text:{format:zodTextFormat(schema,name)},max_output_tokens:aiConfig.maxOutputTokens,store:false});if(!response.output_parsed)throw new Error("empty_output");return response.output_parsed as T;}catch(error){if(error instanceof OpenAI.AuthenticationError)throw new Error("OpenAI API Key 无效，请检查服务端环境变量。");if(error instanceof OpenAI.RateLimitError)throw new Error("AI 服务请求过于频繁，请稍后重试。");if(error instanceof OpenAI.APIConnectionError)throw new Error("暂时无法连接 AI 服务，请稍后重试。");throw new Error("AI 返回内容未通过结构校验，请重试。");}}
 async generateResearch(request:Parameters<LLMProvider["generateResearch"]>[0]){const parsed=await this.parse<{modules:Array<{module:string;title:string;summary:string;keyFacts:string;marketSignals:string;inference:string;marketingMeaning:string;limitations:string;sourceIds:string[]}>}>(request.prompt,researchResponseSchema,"brand_research");const byId=new Map(request.sources.map(item=>[item.sourceId,item]));const modules=parsed.modules.map(module=>({...module,sources:module.sourceIds.map(id=>byId.get(id)).filter((item):item is NonNullable<typeof item>=>Boolean(item))}));if(modules.some(module=>module.sources.length===0))throw new Error("AI 未能为所有研究模块关联有效来源，请重试。");return modules;}
 async generateInsights(request:Parameters<LLMProvider["generateInsights"]>[0]){const parsed=await this.parse<{insights:Array<{type:"CORE"|"PAIN"|"OPPORTUNITY"|"RISK";content:string;evidence:string;researchModules:string[]}>}>(request.prompt,insightResponseSchema,"brand_insights");return parsed.insights.map(item=>({...item,status:"SUGGESTED" as const}));}
 async generateBrief(request:Parameters<LLMProvider["generateBrief"]>[0]){const parsed=await this.parse<Omit<Awaited<ReturnType<LLMProvider["generateBrief"]>>,"markdown">>(request.prompt,briefResponseSchema,"brand_brief");return{...parsed,markdown:briefToMarkdown(request.project.brandName,parsed)};}
}
