import Link from "next/link";
import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, TextareaHTMLAttributes } from "react";

export function Button({ variant = "dark", className = "", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "dark" | "light" }) { return <button className={`button ${variant} ${className}`.trim()} {...props} />; }
export function ButtonLink({ href, children, variant = "dark", className = "" }: { href: string; children: ReactNode; variant?: "dark" | "light"; className?: string }) { return <Link href={href} className={`button ${variant} ${className}`.trim()}>{children}</Link>; }
export function Field({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: ReactNode }) { return <label className="ui-field"><span>{label}</span>{children}{hint && <small>{hint}</small>}{error && <small className="form-error">{error}</small>}</label>; }
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input className="ui-input" {...props} />; }
export function Textarea(props: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className="ui-textarea" {...props} />; }
export function StatusBadge({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "active" | "complete" }) { return <span className={`ui-status ${tone}`}>{children}</span>; }
export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`ui-card ${className}`.trim()}>{children}</section>; }
export function LoadingState() { return <div className="state-page" role="status" aria-live="polite"><span className="state-pulse"/><strong>正在整理内容</strong><p>请稍候，研究工作区马上就好。</p></div>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="empty-card"><h2>{title}</h2><p>{description}</p>{action}</div>; }
export function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="state-page" role="alert"><strong>暂时无法加载</strong><p>{message}</p><div className="state-actions"><ButtonLink href="/projects" variant="light">返回项目列表</ButtonLink><Button onClick={retry}>重新尝试</Button></div></div>; }
export function ConfirmDialog({ open, title, description, confirmLabel = "确认", onCancel, onConfirm }: { open: boolean; title: string; description: string; confirmLabel?: string; onCancel: () => void; onConfirm: () => void }) { if (!open) return null; return <div className="dialog-backdrop" role="presentation" onMouseDown={onCancel}><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title" onMouseDown={event => event.stopPropagation()}><span className="section-label">确认操作</span><h2 id="confirm-title">{title}</h2><p>{description}</p><div><Button variant="light" onClick={onCancel}>取消</Button><Button autoFocus onClick={onConfirm}>{confirmLabel}</Button></div></div></div>; }
