ALTER TABLE "Research" ADD COLUMN "inference" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Source" ADD COLUMN "retrievedAt" DATETIME NOT NULL DEFAULT '1970-01-01T00:00:00.000Z';
ALTER TABLE "Source" ADD COLUMN "sourceType" TEXT NOT NULL DEFAULT 'OTHER';
